language: java
jdk:
   - openjdk7
before_install:
    - sudo apt-get update
script: 
   - bash bakeit.sh
after_success:
  - bash deployProd.sh
env:
  global:
    secure: OdNUxIew00hMwAL3vb30d4vkRkW+FnRXZ1iXu0Yolw0dJnHsKBXhLXZbKgdVljrWXjOb1NWsaWk8TPdCIfw025h5dz2g+wCYa1vlRMdvkQoZX1isqRJOncNbjFXk21e/W9mZvESbuO0QWtI3Z8suuMp01HsFJtLv7CLl6DO5VgI+2xKorYR24dGTDPjGRe4tLBwQ4xrRxIqilchpJ8ppBYTZTh4/QwwA1ZvnbtwFHSGs4P9RwmIv0zwcq5UQ5rtPBCrOoumWKMWizlk9ZeTF5+CspnUwJVPs4vffpcw8FPQfbXpT0h6+hHFQ4advPYD3Tm14UmD+HskRU2v0KvRevF9qQVIy1JJV5YxGPk6KuGCLSrVwlUGTB/UGuNG1U8I1Rftl2e5xZS3bhrRP++JmqNh4PsgTu3mlLCxyyZ6+H9bWXMCat+CTCZLggndEhjIIVUlJbboLxUgqbA7hxU7OB8+jg2UTJT5V0qk4+tmNLj0/YOrIb10WwD9UhP7RwZ8S+h846D5U/nXBuI29axq/4IcI3Kz/mAm+H4ToiKZkcMBZi56kesszGSH6pqfJNfy8zNrCg09YxXcrhSHv0TU7+otHqaljdhgp9mD2P0dCdndatuBzCsePCZYTyvHiDlyVxNLNTGomcV4m7XPMSdqkvDKFw6obsRPkT3PBEFkNHF0=
